package com.emi.wms.bean;

import java.io.Serializable;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;
@EmiTable(name = "AA_Department")
public class AaDepartment implements Serializable{

	private static final long serialVersionUID = -1385529744577413555L;
	
	@EmiColumn(name = "pk", increment=true)
    private Integer pk;
	@EmiColumn(name = "gid", ID = true)
    private String gid;
	@EmiColumn(name = "notes")
    private String notes;//部门备注
	@EmiColumn(name = "depcode")
    private String depcode;//部门编码
	@EmiColumn(name = "depname")
    private String depname;//部门名称
	@EmiColumn(name = "principal")
    private String principal;//部门负责人
	@EmiColumn(name = "depparentuid")
    private String depparentuid;//父级部门UID
	
    private String depparentcode;//父级部门编码
    private String depparentname;//父级部门名称
    
	
	@EmiColumn(name = "last")
    private Integer last;//是否末级
	@EmiColumn(name = "layer")
    private Integer layer;//级次
	
    private Date begintimes;
    private Date endtimes;
    
	@EmiColumn(name = "orggid")
    private String orggid;//组织ID
	@EmiColumn(name = "sobgid")
    private String sobgid;//帐套ID
	@EmiColumn(name = "isdel")
    private Integer isdel;//是否删除

	
	
	
    public String getDepparentname() {
		return depparentname;
	}

	public void setDepparentname(String depparentname) {
		this.depparentname = depparentname;
	}

	public String getDepparentuid() {
		return depparentuid;
	}

	public void setDepparentuid(String depparentuid) {
		this.depparentuid = depparentuid;
	}

	public String getDepparentcode() {
		return depparentcode;
	}

	public void setDepparentcode(String depparentcode) {
		this.depparentcode = depparentcode;
	}

	public String getOrggid() {
		return orggid;
	}

	public void setOrggid(String orggid) {
		this.orggid = orggid;
	}

	public String getSobgid() {
		return sobgid;
	}

	public void setSobgid(String sobgid) {
		this.sobgid = sobgid;
	}

	public Integer getIsdel() {
		return isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.pk
     *
     * @return the value of dbo.AA_Department.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.pk
     *
     * @param pk the value for dbo.AA_Department.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.gid
     *
     * @return the value of dbo.AA_Department.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.gid
     *
     * @param gid the value for dbo.AA_Department.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.notes
     *
     * @return the value of dbo.AA_Department.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.notes
     *
     * @param notes the value for dbo.AA_Department.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.depCode
     *
     * @return the value of dbo.AA_Department.depCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDepcode() {
        return depcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.depCode
     *
     * @param depcode the value for dbo.AA_Department.depCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDepcode(String depcode) {
        this.depcode = depcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.depName
     *
     * @return the value of dbo.AA_Department.depName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.depName
     *
     * @param depname the value for dbo.AA_Department.depName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDepname(String depname) {
        this.depname = depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.principal
     *
     * @return the value of dbo.AA_Department.principal
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.principal
     *
     * @param principal the value for dbo.AA_Department.principal
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPrincipal(String principal) {
        this.principal = principal;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.last
     *
     * @return the value of dbo.AA_Department.last
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.last
     *
     * @param last the value for dbo.AA_Department.last
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLast(Integer last) {
        this.last = last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.layer
     *
     * @return the value of dbo.AA_Department.layer
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.layer
     *
     * @param layer the value for dbo.AA_Department.layer
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.beginTimes
     *
     * @return the value of dbo.AA_Department.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBegintimes() {
        return begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.beginTimes
     *
     * @param begintimes the value for dbo.AA_Department.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBegintimes(Date begintimes) {
        this.begintimes = begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Department.endTimes
     *
     * @return the value of dbo.AA_Department.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getEndtimes() {
        return endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Department.endTimes
     *
     * @param endtimes the value for dbo.AA_Department.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEndtimes(Date endtimes) {
        this.endtimes = endtimes;
    }



}