package com.emi.wms.bean;

import java.util.Date;

public class TaskC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.taskUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.distributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date distributetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.shouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date shouldcplttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecdeptuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecroleuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.recUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String recuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.recTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date rectime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Task_C.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer bisover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.pk
     *
     * @return the value of dbo.WM_Task_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.pk
     *
     * @param pk the value for dbo.WM_Task_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.gid
     *
     * @return the value of dbo.WM_Task_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.gid
     *
     * @param gid the value for dbo.WM_Task_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.notes
     *
     * @return the value of dbo.WM_Task_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.notes
     *
     * @param notes the value for dbo.WM_Task_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.taskUid
     *
     * @return the value of dbo.WM_Task_C.taskUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskuid() {
        return taskuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.taskUid
     *
     * @param taskuid the value for dbo.WM_Task_C.taskUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskuid(String taskuid) {
        this.taskuid = taskuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.distributeTime
     *
     * @return the value of dbo.WM_Task_C.distributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDistributetime() {
        return distributetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.distributeTime
     *
     * @param distributetime the value for dbo.WM_Task_C.distributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDistributetime(Date distributetime) {
        this.distributetime = distributetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.shouldCpltTime
     *
     * @return the value of dbo.WM_Task_C.shouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getShouldcplttime() {
        return shouldcplttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.shouldCpltTime
     *
     * @param shouldcplttime the value for dbo.WM_Task_C.shouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setShouldcplttime(Date shouldcplttime) {
        this.shouldcplttime = shouldcplttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.aptRecDeptuid
     *
     * @return the value of dbo.WM_Task_C.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecdeptuid() {
        return aptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.aptRecDeptuid
     *
     * @param aptrecdeptuid the value for dbo.WM_Task_C.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecdeptuid(String aptrecdeptuid) {
        this.aptrecdeptuid = aptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.aptRecRoleUid
     *
     * @return the value of dbo.WM_Task_C.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecroleuid() {
        return aptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.aptRecRoleUid
     *
     * @param aptrecroleuid the value for dbo.WM_Task_C.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecroleuid(String aptrecroleuid) {
        this.aptrecroleuid = aptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.aptRecUserUid
     *
     * @return the value of dbo.WM_Task_C.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecuseruid() {
        return aptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.aptRecUserUid
     *
     * @param aptrecuseruid the value for dbo.WM_Task_C.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecuseruid(String aptrecuseruid) {
        this.aptrecuseruid = aptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.recUserUid
     *
     * @return the value of dbo.WM_Task_C.recUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRecuseruid() {
        return recuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.recUserUid
     *
     * @param recuseruid the value for dbo.WM_Task_C.recUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecuseruid(String recuseruid) {
        this.recuseruid = recuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.recTime
     *
     * @return the value of dbo.WM_Task_C.recTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getRectime() {
        return rectime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.recTime
     *
     * @param rectime the value for dbo.WM_Task_C.recTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRectime(Date rectime) {
        this.rectime = rectime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.completeTime
     *
     * @return the value of dbo.WM_Task_C.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.completeTime
     *
     * @param completetime the value for dbo.WM_Task_C.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Task_C.bIsOver
     *
     * @return the value of dbo.WM_Task_C.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getBisover() {
        return bisover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Task_C.bIsOver
     *
     * @param bisover the value for dbo.WM_Task_C.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBisover(Integer bisover) {
        this.bisover = bisover;
    }
}