package com.emi.wms.bean;

import java.io.Serializable;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;

@EmiTable(name="unit")
public class Unit implements Serializable{

	private static final long serialVersionUID = -3830191886411944441L;

	@EmiColumn(increment=true,name="pk")
    private Integer pk;
	
	@EmiColumn(ID=true,name="gid")
    private String gid;
	
	@EmiColumn(name="unitname")
    private String unitname;//单位编码名称
	
	@EmiColumn(name="unitcode")
    private String unitcode;//单位编码
	
	@EmiColumn(name="sobid")
    private String sobid;//帐套编码
	
	@EmiColumn(name="orgid")
    private String orgid;//组织编码
	
	@EmiColumn(name="isDel")
	private Integer isDel;//删除标识 1删除 0未删除

    
    
    
    public Integer getIsDel() {
		return isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.pk
     *
     * @return the value of dbo.unit.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.pk
     *
     * @param pk the value for dbo.unit.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.gid
     *
     * @return the value of dbo.unit.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.gid
     *
     * @param gid the value for dbo.unit.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.unitName
     *
     * @return the value of dbo.unit.unitName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.unitName
     *
     * @param unitname the value for dbo.unit.unitName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.unitCode
     *
     * @return the value of dbo.unit.unitCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUnitcode() {
        return unitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.unitCode
     *
     * @param unitcode the value for dbo.unit.unitCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.sobId
     *
     * @return the value of dbo.unit.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.sobId
     *
     * @param sobid the value for dbo.unit.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unit.orgId
     *
     * @return the value of dbo.unit.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unit.orgId
     *
     * @param orgid the value for dbo.unit.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}