package com.emi.wms.bean;

import java.math.BigDecimal;

public class WmNowstock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.notes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String goodsuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String whuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.toPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal toputinnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.toPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal toputoutnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.transfersPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal transfersputinnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.transfersPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal transfersputoutnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String orggid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_NowStock.available
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.pk
     *
     * @return the value of dbo.WM_NowStock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.pk
     *
     * @param pk the value for dbo.WM_NowStock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.gid
     *
     * @return the value of dbo.WM_NowStock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.gid
     *
     * @param gid the value for dbo.WM_NowStock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.notes
     *
     * @return the value of dbo.WM_NowStock.notes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.notes
     *
     * @param notes the value for dbo.WM_NowStock.notes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.goodsUid
     *
     * @return the value of dbo.WM_NowStock.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGoodsuid() {
        return goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.goodsUid
     *
     * @param goodsuid the value for dbo.WM_NowStock.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGoodsuid(String goodsuid) {
        this.goodsuid = goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.number
     *
     * @return the value of dbo.WM_NowStock.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.number
     *
     * @param number the value for dbo.WM_NowStock.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.whUid
     *
     * @return the value of dbo.WM_NowStock.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getWhuid() {
        return whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.whUid
     *
     * @param whuid the value for dbo.WM_NowStock.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setWhuid(String whuid) {
        this.whuid = whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.toPutinNum
     *
     * @return the value of dbo.WM_NowStock.toPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getToputinnum() {
        return toputinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.toPutinNum
     *
     * @param toputinnum the value for dbo.WM_NowStock.toPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setToputinnum(BigDecimal toputinnum) {
        this.toputinnum = toputinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.toPutoutNum
     *
     * @return the value of dbo.WM_NowStock.toPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getToputoutnum() {
        return toputoutnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.toPutoutNum
     *
     * @param toputoutnum the value for dbo.WM_NowStock.toPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setToputoutnum(BigDecimal toputoutnum) {
        this.toputoutnum = toputoutnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.transfersPutinNum
     *
     * @return the value of dbo.WM_NowStock.transfersPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getTransfersputinnum() {
        return transfersputinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.transfersPutinNum
     *
     * @param transfersputinnum the value for dbo.WM_NowStock.transfersPutinNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setTransfersputinnum(BigDecimal transfersputinnum) {
        this.transfersputinnum = transfersputinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.transfersPutoutNum
     *
     * @return the value of dbo.WM_NowStock.transfersPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getTransfersputoutnum() {
        return transfersputoutnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.transfersPutoutNum
     *
     * @param transfersputoutnum the value for dbo.WM_NowStock.transfersPutoutNum
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setTransfersputoutnum(BigDecimal transfersputoutnum) {
        this.transfersputoutnum = transfersputoutnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.sobGid
     *
     * @return the value of dbo.WM_NowStock.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.sobGid
     *
     * @param sobgid the value for dbo.WM_NowStock.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.orgGid
     *
     * @return the value of dbo.WM_NowStock.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.orgGid
     *
     * @param orggid the value for dbo.WM_NowStock.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_NowStock.available
     *
     * @return the value of dbo.WM_NowStock.available
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_NowStock.available
     *
     * @param available the value for dbo.WM_NowStock.available
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAvailable(BigDecimal available) {
        this.available = available;
    }
}